---
title: "p8105_hw2_xm2356"
author: "Xinyin Miao (xm2356)"
date: "2025-09-27"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(readxl)
library(knitr)
```

# Problem 1

## Clean data in pols-month

```{r}
## load data
pols_df = read_csv("data/fivethirtyeight_datasets/pols-month.csv")

## clean data
pols_cleaned = pols_df |> 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),

    month = case_when(
      month == 1 ~ "January", month == 2 ~ "February", month == 3 ~ "March",
      month == 4 ~ "April", month == 5 ~ "May", month == 6 ~ "June",
      month == 7 ~ "July", month == 8 ~ "August", month == 9 ~ "September",
      month == 10 ~ "October", month == 11 ~ "November", month == 12 ~ "December",
      TRUE ~ as.character(month)
    ),
    president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop",
      TRUE ~ NA_character_
    )
  ) |> 
  select(-prez_dem, -prez_gop, -day) |> 
  select (year, month, president, everything())
  
pols_cleaned
```


## Clean data in snp

```{r}
## load data
snp_df = read_csv("data/fivethirtyeight_datasets/snp.csv")

## clean data
snp_cleaned = snp_df |> 
  separate(date, into = c("month_num", "day", "year_short"), sep = "/", convert = TRUE)  |> 

  mutate(
    year = case_when(
      year_short <= 49 ~ year_short + 2000,
      year_short >= 50 ~ year_short + 1900,
    ),
    month = case_when(
      month_num == 1 ~ "January", month_num == 2 ~ "February", month_num == 3 ~ "March",
      month_num == 4 ~ "April", month_num == 5 ~ "May", month_num == 6 ~ "June",
      month_num == 7 ~ "July", month_num == 8 ~ "August", month_num == 9 ~ "September",
      month_num == 10 ~ "October", month_num == 11 ~ "November", month_num == 12 ~ "December",
      TRUE ~ NA_character_
      )
  )  |>  
  select(year, month, snp_value = close) |> 
    # arrange by year and month
  arrange(year, month)

snp_cleaned
```


## Clean data in unemployment

```{r}
## load data
unemployment_df = read_csv("data/fivethirtyeight_datasets/unemployment.csv")

## tidy data
unemployment_cleaned = unemployment_df |> 
  rename(year = Year) |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month_abbr",
    values_to = "unemployment_rate"
  ) |> 
mutate(
    month = case_when(
      month_abbr == "Jan" ~ "January", month_abbr == "Feb" ~ "February",
      month_abbr == "Mar" ~ "March", month_abbr == "Apr" ~ "April",
      month_abbr == "May" ~ "May", month_abbr == "Jun" ~ "June",
      month_abbr == "Jul" ~ "July", month_abbr == "Aug" ~ "August",
      month_abbr == "Sep" ~ "September", month_abbr == "Oct" ~ "October",
      month_abbr == "Nov" ~ "November", month_abbr == "Dec" ~ "December",
      TRUE ~ NA_character_
    )
) |> 
select(year, month, unemployment_rate) |> 
arrange(year, month)

unemployment_cleaned
```

## Join the data

```{r}
merged_df = pols_cleaned |> 
  left_join(snp_cleaned, by = c("year", "month")) |> 
  left_join(unemployment_cleaned, by = c("year", "month"))

merged_df
```

















