p8105_hw2_xm2356
================
Xinyin Miao (xm2356)
2025-09-27

# Problem 1

## Clean data in pols-month

``` r
## load data
pols_df = read_csv("data/fivethirtyeight_datasets/pols-month.csv")

## clean data
pols_cleaned = pols_df |> 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),

    month = case_when(
      month == 1 ~ "January", month == 2 ~ "February", month == 3 ~ "March",
      month == 4 ~ "April", month == 5 ~ "May", month == 6 ~ "June",
      month == 7 ~ "July", month == 8 ~ "August", month == 9 ~ "September",
      month == 10 ~ "October", month == 11 ~ "November", month == 12 ~ "December",
      TRUE ~ as.character(month)
    ),
    president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop",
      TRUE ~ NA_character_
    )
  ) |> 
  select(-prez_dem, -prez_gop, -day) |> 
  select (year, month, president, everything())
  
pols_cleaned
```

    ## # A tibble: 822 × 9
    ##     year month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <int> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January   dem            23      51     253      23      45     198
    ##  2  1947 February  dem            23      51     253      23      45     198
    ##  3  1947 March     dem            23      51     253      23      45     198
    ##  4  1947 April     dem            23      51     253      23      45     198
    ##  5  1947 May       dem            23      51     253      23      45     198
    ##  6  1947 June      dem            23      51     253      23      45     198
    ##  7  1947 July      dem            23      51     253      23      45     198
    ##  8  1947 August    dem            23      51     253      23      45     198
    ##  9  1947 September dem            23      51     253      23      45     198
    ## 10  1947 October   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows

The pols-month.csv dataset contained monthly political control data,
including presidential party affiliation (prez_gop/prez_dem) and the
distribution of governorships and congressional seats, starting from
1947.

## Clean data in snp

``` r
## load data
snp_df = read_csv("data/fivethirtyeight_datasets/snp.csv")

## clean data
snp_cleaned = snp_df |> 
  separate(date, into = c("month_num", "day", "year_short"), sep = "/", convert = TRUE)  |> 

  mutate(
    year = case_when(
      year_short <= 49 ~ year_short + 2000,
      year_short >= 50 ~ year_short + 1900,
    ),
    month = case_when(
      month_num == 1 ~ "January", month_num == 2 ~ "February", month_num == 3 ~ "March",
      month_num == 4 ~ "April", month_num == 5 ~ "May", month_num == 6 ~ "June",
      month_num == 7 ~ "July", month_num == 8 ~ "August", month_num == 9 ~ "September",
      month_num == 10 ~ "October", month_num == 11 ~ "November", month_num == 12 ~ "December",
      TRUE ~ NA_character_
      )
  )  |>  
  select(year, month, snp_value = close) |> 
    # arrange by year and month
  arrange(year, month)

snp_cleaned
```

    ## # A tibble: 787 × 3
    ##     year month    snp_value
    ##    <dbl> <chr>        <dbl>
    ##  1  1950 April         18.0
    ##  2  1950 August        18.4
    ##  3  1950 December      20.4
    ##  4  1950 February      17.2
    ##  5  1950 January       17.0
    ##  6  1950 July          17.8
    ##  7  1950 June          17.7
    ##  8  1950 March         17.3
    ##  9  1950 May           18.8
    ## 10  1950 November      19.5
    ## # ℹ 777 more rows

The snp.csv file provided the monthly closing value of the S&P 500
index, tracking market performance across the period.

## Clean data in unemployment

``` r
## load data
unemployment_df = read_csv("data/fivethirtyeight_datasets/unemployment.csv")

## tidy data
unemployment_cleaned = unemployment_df |> 
  rename(year = Year) |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month_abbr",
    values_to = "unemployment_rate"
  ) |> 
mutate(
    month = case_when(
      month_abbr == "Jan" ~ "January", month_abbr == "Feb" ~ "February",
      month_abbr == "Mar" ~ "March", month_abbr == "Apr" ~ "April",
      month_abbr == "May" ~ "May", month_abbr == "Jun" ~ "June",
      month_abbr == "Jul" ~ "July", month_abbr == "Aug" ~ "August",
      month_abbr == "Sep" ~ "September", month_abbr == "Oct" ~ "October",
      month_abbr == "Nov" ~ "November", month_abbr == "Dec" ~ "December",
      TRUE ~ NA_character_
    )
) |> 
select(year, month, unemployment_rate) |> 
arrange(year, month)

unemployment_cleaned
```

    ## # A tibble: 816 × 3
    ##     year month    unemployment_rate
    ##    <dbl> <chr>                <dbl>
    ##  1  1948 April                  3.9
    ##  2  1948 August                 3.9
    ##  3  1948 December               4  
    ##  4  1948 February               3.8
    ##  5  1948 January                3.4
    ##  6  1948 July                   3.6
    ##  7  1948 June                   3.6
    ##  8  1948 March                  4  
    ##  9  1948 May                    3.5
    ## 10  1948 November               3.8
    ## # ℹ 806 more rows

The unemployment.csv dataset held the U.S. unemployment rate, originally
in a wide format with each month as a separate column. After cleaning
and merging, the resulting dataset has 816 observations and 3 variables.

## Join the data

``` r
merged_df = pols_cleaned |> 
  left_join(snp_cleaned, by = c("year", "month")) |> 
  left_join(unemployment_cleaned, by = c("year", "month"))

merged_df
```

    ## # A tibble: 822 × 11
    ##     year month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January   dem            23      51     253      23      45     198
    ##  2  1947 February  dem            23      51     253      23      45     198
    ##  3  1947 March     dem            23      51     253      23      45     198
    ##  4  1947 April     dem            23      51     253      23      45     198
    ##  5  1947 May       dem            23      51     253      23      45     198
    ##  6  1947 June      dem            23      51     253      23      45     198
    ##  7  1947 July      dem            23      51     253      23      45     198
    ##  8  1947 August    dem            23      51     253      23      45     198
    ##  9  1947 September dem            23      51     253      23      45     198
    ## 10  1947 October   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: snp_value <dbl>, unemployment_rate <dbl>

This project merged three datasets provided by FiveThirtyEight. The
resulting tidy dataset, created by merging the three files using
left_join, has 822 observations and 11 variables. The data spans the
years from 1947 to 2015. Key variables include year, month, president
(gop or dem), snp_value, and unemployment_rate.
